### ISSUE TITLE
Skip creating index.html

### ISSUE THREAD

**Issue by docforcedev** [Sauloxd/stories#10]
We want to create review apps, but don't want to remove the existing index.html --- Can we have an option to skip index.html creation?

**Comment by docforcedev** [comment]
@Sauloxd any chance about this?

**Comment by Sauloxd** [comment]
Sure, I can add this flag! 
The idea is to improve this action to make a comment in pull request to inform the correct URL for the app, making the index page useless!
I'll try to tackle this soon

**Comment by Sauloxd** [comment]
Implemented in #17! Please feel free to reopen if this implementation is not enough :)

**Comment by justinr1234** [comment]
> Implemented in #17! Please feel free to reopen if this implementation is not enough :)

Thanks!
