### ISSUE TITLE
Deprecated set-env

### ISSUE THREAD

**Issue by docforcedev** [Sauloxd/stories#6]
Seeing this error message, looks like you need to bump the `@actions/core` package maybe?

```
/usr/bin/git config --global user.name review-app-action-user
/usr/bin/git config --global user.email review-app-action-email
/usr/bin/git config pull.rebase true
Error: Unable to process command '::set-env name=PUBLIC_URL::<hidden>' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by docforcedev** [comment]
This line causes the bug: https://github.com/Sauloxd/review-apps/blob/master/packages/action/src/other-events.js#L43

**Comment by docforcedev** [comment]
`Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions.`

**Comment by Sauloxd** [comment]
Sure thing! I'll look into it, thanks

**Comment by Sauloxd** [comment]
@docforcedev Just published a new release in github actions with this fix: v.1.3.3
Please let me know if this error persists or if something else appears! 👍
