### ISSUE TITLE
Optional build-cmd

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [Sauloxd/stories#9]
When running in GitHub Actions, the build-cmd is unnecessary, because I can just add a build step before the `uses` step. The build-cmd input also can't do things like `cd demo && pnpm run build && touch .nojekyll`, so I had to build it before the step and change the build-cmd to `echo "Already built"`. It would be easier if I could just not specify build-cmd and it didn't run it.

**Comment by Sauloxd** [comment]
Good idea! I'll try to tackle this and other issues this weekend!

**Comment by Sauloxd** [comment]
Fixed in #15
